trigger:
 - master
  
pr:
  branches:
    include:
      - dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHubConnnection'
        repository: 'anuj730/repo1'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'DockerHubConnnection'
        repository: 'anuj730/repo1'
        command: 'push'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

